### ISSUE TITLE
[BUG] Does not load on 40xx, artifacts of the image on the screen

### ISSUE THREAD

**Issue by mrMagHub** [loki666/ROCKNIX#10]
Does not load on 40xx, artifacts of the image on the screen. If you click on the buttons, the image with artifacts changes, that is, the system itself has booted up and is working.
![40xx](https://github.com/user-attachments/assets/5645b8fc-b59e-4473-99f4-eb525080e2cf)

**Comment by loki666** [comment]
Looks like you didn't update the DTB in extlinux/extlinux.conf

**Comment by mrMagHub** [comment]
img installed via rufus onto a formatted SD card.
MuOS also had a problem with the screen; 35xx and 40xx have differences in terms of screens.

I’m not the only one with this problem, there are similar reviews on 4pda.to

**Comment by loki666** [comment]
so you did changes the dtb in extlinux/extlinux.conf file?
if so, it, indeed, seems like Anbernic released a 40XX with a new screen we need to add support for

**Comment by mrMagHub** [comment]
100% changed extlinux/extlinux.conf
Yes, in 40xx there are differences with the display; other custom firmware had the same problem.

**Comment by loki666** [comment]
Damn Anbernic..
Thanks for reporting we'll look for it

If you could paste the DTB from a running device on Anbernic FW that would help a lot.

**Comment by loki666** [comment]
install this https://github.com/FlorianMarsch/rg35xxp-unchained
connect to ssh with root/root
and then you can print the dtb with
cat /proc/device-tree

**Comment by mrMagHub** [comment]
It turned out this way, but it was executed on MuOS firmware....


~ # cat /proc/device-tree/
cat: read error: Is a directory
~ # cat /proc/device-tree/board
cat: can't open '/proc/device-tree/board': No such file or directory
~ # cat /proc/device-tree/board
cat: can't open '/proc/device-tree/board': No such file or directory
~ # cd /proc/device-tree/
/proc/device-tree # ls
#address-cells                 clocks                         intc-nmi@07010320              model                          s_brom                         sunxi-chipid@03006200
#size-cells                    compatible                     interrupt-controller@0         n_brom                         s_cpuscfg                      sunxi-sid-ng@03006000
__symbols__                    cpus                           interrupt-controller@03020000  name                           soc@03000000                   sunxi-sid@03006000
aliases                        dram                           interrupt-parent               opp_l_table                    sram_a1                        timer_arch
axp2202-parameter              dramfreq                       iommu@030f0000                 pmu                            sram_a2                        uboot
box_start_os0                  firmware                       ion                            prcm                           sram_ctrl
chosen                         gpu@0x01800000                 memory@40000000                psci                           standby_param
/proc/device-tree #

**Comment by kikuchan** [comment]
If you don't mind a warranty, can you open the back panel and read an assy part serial# (likely on the cable) of the LCD panel to be sure?
If it is other than "YLM-LBV0400001X-V1", that means the panel has not been supported yet.

Additionally, if you can access to the UART, the boot log of the stock image would be very helpful.

Just a guess, but I think it's worth to try "sun50i-h700-anbernic-rg35xx-plus-**rev6-panel**.dtb" to see whether if the panels are compatible.

**Comment by mrMagHub** [comment]
There is no way to open the panel, tell me how to read the log via UART, or other ways to find out dtb?

**Comment by loki666** [comment]
for the dtb, you need to exec `dtc -I fs /sys/firmware/devicetree/base` but I'm not sure if `dtc` is installed on Anbernic FW

**Comment by mrMagHub** [comment]
result exec  "find /proc/device-tree/ -type f -exec head {} + > device-tree-from-proc"
attached files
[device-tree-from-procSTOC.txt](https://github.com/user-attachments/files/18076648/device-tree-from-procSTOC.txt)
[device-tree-from-procMuOS.txt](https://github.com/user-attachments/files/18076649/device-tree-from-procMuOS.txt)

**Comment by loki666** [comment]
@mrMagHub 
could you retrive the fdt file using
`scp root@<device IP>:/sys/firmware/fdt rg40xx-h.dtb` on stock with ssh enabled
and post the file `rg40xx-h.dtb` here

thanks

**Comment by mrMagHub** [comment]
@loki666 I did it. I had to make an archive, otherwise it won't attach
[rg40xx-h.zip](https://github.com/user-attachments/files/18106141/rg40xx-h.zip)

**Comment by loki666** [comment]
@kikuchan can you do your magic with this dtb ?

**Comment by kikuchan** [comment]
Unfortunately, if it is a new LCD panel, the DTB is (helpful but) insufficient to add support... :cry:
It requires an init-sequence (binary data) taken from the actual device by using a logic-analyzer.
(pure software solution hasn't been found yet)

Is there anyone who got trouble with the panel, can open the back panel?
I want to confirm that is a 100% hardware problem, and then maybe I can buy the panel from Anbernic. :wink:

**Comment by loki666** [comment]
I see...

**Comment by loki666** [comment]
@mrMagHub you don't need to open the lcd panel itself, just open the device, and access the back of the panel (you may have to unscrew the PCB from the device shell to access it)
and detach the LCD stripe (there should be a small lever to unlock the stripe)

**Comment by mrMagHub** [comment]
@loki666 photo 
![Uploading IMG_20241212_114415.jpg…]()
YLM-LBV0400001X-V1

**Comment by loki666** [comment]
Thanks, upload seems to have failed, but the part number is enough
@kikuchan I think it's the one we are already using right ?

**Comment by mrMagHub** [comment]
![IMG_20241212_114415](https://github.com/user-attachments/assets/fc8de1fe-f515-41ad-bf07-34f588f89372)

**Comment by kikuchan** [comment]
@mrMagHub Thank you!

@loki666 Yes, right!
It means something wrong from a software perspective.

in `nv3052c_prepare`:
```c
	/* Reset the chip */
	gpiod_set_value_cansleep(priv->reset_gpio, 1);
	usleep_range(10, 1000);
	gpiod_set_value_cansleep(priv->reset_gpio, 0);
	usleep_range(5000, 20000);
```
gpio assignment is properly setup?
need to tweak a sleep range?
just a guess...

**Comment by loki666** [comment]
@kikuchan 
should I try

```
	/* Reset the chip */
	gpiod_set_value_cansleep(priv->reset_gpio, 1);
	usleep_range(100, 1000);
	gpiod_set_value_cansleep(priv->reset_gpio, 0);
	usleep_range(5000, 20000);
```

**Comment by kikuchan** [comment]
Oh, sorry.
something like much longer, for example:
```c
	/* Reset the chip */
	gpiod_set_value_cansleep(priv->reset_gpio, 1);
	msleep(5);
	gpiod_set_value_cansleep(priv->reset_gpio, 0);
	msleep(120);
```

**Comment by loki666** [comment]
ok

**Comment by loki666** [comment]
@mrMagHub can you test this release
https://github.com/loki666/ROCKNIX/releases/tag/rg40xx-h-panel-test-1

**Comment by mrMagHub** [comment]
@loki666 unfortunately no changes.
I flashed the SD card twice, completely deleting partitions
![IMG_20241214_235323](https://github.com/user-attachments/assets/ee0ac56b-bcb5-4434-a4a9-c4063d6e02b3)

**Comment by loki666** [comment]
so you are having this issue on both your RG40XX-V and -H...
can you paste your file /extlinux/extlinux.conf ? in ROCKNIX partition

this looks exactly as if you are trying to boot a 35xx dtb on a 40xx device

**Comment by mrMagHub** [comment]
I can't find the file in this path.
the boot directory is also empty.

**Comment by loki666** [comment]
plug the sd card in your computer

**Comment by mrMagHub** [comment]
@loki666 
[extlinux.zip](https://github.com/user-attachments/files/18139401/extlinux.zip)

**Comment by loki666** [comment]
see https://rocknix.org/devices/anbernic/rg40xx-v/#installation and https://rocknix.org/devices/anbernic/rg40xx-h/#installation

**Comment by mrMagHub** [comment]
@loki666 it works, thanks
![IMG_20241215_120125](https://github.com/user-attachments/assets/8bc15fd6-8d2d-4f25-be3d-b7da690db103)
